export const actionTypes  = {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    ADD_TODO: 'ADD_TODO',
    RESET_TODOS: 'RESET_TODOS',
    LOAD_TODOS: 'LOAD_TODOS',
    LOAD_USER: 'LOAD_USER',
    TOGGLE_MENU: 'TOGGLE_MENU'
};